name: Release Obsidian theme

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        # --- ADD THIS BLOCK ---
        permissions:
            contents: write # Grants permission to write to the repository content, which includes creating releases and uploading assets.
            # Or, more specifically for releases:
            # releases: write
        # ----------------------

        steps:
            - uses: actions/checkout@v3

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"

                  gh release create "$tag" \
                    --title="$tag" \
                    --generate-notes \
                    --draft \
                    manifest.json theme.css
